# Generated by Django 6.1 on 2026-08-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='reconciliation.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('category_code', models.CharField(blank=True, max_length=50, null=True)),
                ('actor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_a_records', to='reconciliation.location')),
            ],
        ),
        migrations.CreateModel(
            name='SystemBRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=50)),
                ('raw_record_ref', models.CharField(max_length=100)),
                ('normalized_record_ref', models.CharField(max_length=100)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_b_records', to='reconciliation.location')),
            ],
        ),
    ]
