# Generated by Django 6.1 on 2026-08-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systembrecord',
            name='import_errors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='systembrecord',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
