# Generated by Django 6.1 on 2026-08-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_systembrecord_import_errors_systembrecord_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='import_errors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='location',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='import_errors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
