# Generated by Django 6.1 on 2026-08-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_location_import_errors_location_raw_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systembrecord',
            name='entry_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
